// =====================================================================
//  YOUR TUMBLERS  —  add, remove, or edit products here.
//
//  Each product is one { ... } block. To add a new one, copy a whole
//  block (from { to },) and paste it below the last one, then change it.
//
//  shop        which tab it shows up in: "mom", "dad", or "custom"
//  id          a short unique name, no spaces (used behind the scenes)
//  name        what customers see
//  price       in dollars, no $ sign (e.g. 29.99)
//  size        e.g. "20 oz skinny"
//  description a short note about the design (kept for your records; not shown on the shop cards)
//  image       the photo file inside the "images" folder
//  inStock     true = can be bought, false = shows "Sold out"
//  personalize true = shows a box where the buyer can type a name/text
//  personalizeHint  the grey hint text inside that box (optional)
//  badge       a little sticker on the photo, like "New" or "Our fave" (use "" for none)
// =====================================================================

window.PRODUCTS = [
  // ---------------------------- MOM ----------------------------
  {
    shop: "mom",
    id: "pickle-party",
    name: "Pickle Party",
    price: 14.99,
    size: "20 oz skinny",
    description: "Our signature Pickled Sticker brand cup.",
    image: "images/pickle-party.png",
    inStock: true,
    personalize: false,
    badge: "Our brand cup",
  },
  {
    shop: "mom",
    id: "floral-dream",
    name: "Floral Dream",
    price: 19.99,
    size: "20 oz skinny",
    description: "Vintage tulips, roses and wildflowers wrapped all the way around.",
    image: "images/floral-dream.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
  },
  {
    shop: "mom",
    id: "sunset-glow",
    name: "Sunset Glow",
    price: 19.99,
    size: "20 oz skinny",
    description: "Dreamy pink-and-gold sunset over still water, with roses and golden drips.",
    image: "images/sunset-glow.jpg",
    inStock: true,
    personalize: false,
    badge: "",
  },
  {
    shop: "mom",
    id: "ocean-swirl",
    name: "Ocean Swirl",
    price: 19.99,
    size: "20 oz skinny",
    description: "Swirling turquoise and cobalt waves with white sea foam.",
    image: "images/ocean-swirl.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
  },
  {
    shop: "mom",
    id: "midnight-stars",
    name: "Midnight Stars",
    price: 19.99,
    size: "20 oz skinny",
    description: "Golden moons and stars in a dreamy purple night sky.",
    image: "images/midnight-stars.jpg",
    inStock: true,
    personalize: false,
    badge: "",
  },
  {
    shop: "mom",
    id: "mama-name",
    name: "Mama Name Tumbler",
    price: 19.99,
    size: "20 oz skinny",
    description: "Blush pink marble with peonies and her name in script (sample shows Betty).",
    image: "images/mama-name.jpg",
    inStock: true,
    personalize: true,
    personalizeHint: "Name to add, e.g. Betty or Mama",
    badge: "Personalize it",
  },

  // ---------------------------- DAD ----------------------------
  {
    shop: "dad",
    id: "grill-master",
    name: "Grill Master",
    price: 19.99,
    size: "20 oz skinny",
    description: "For the guy who's been 'checking the burgers' for 45 minutes.",
    image: "images/grill-master.svg",
    inStock: true,
    personalize: false,
    badge: "Dad fave",
  },
  {
    shop: "dad",
    id: "fishing-buddy",
    name: "Gone Fishin'",
    price: 19.99,
    size: "20 oz skinny",
    description: "Lake days, early mornings, and the one that got away.",
    image: "images/fishing-buddy.svg",
    inStock: true,
    personalize: false,
    badge: "",
  },
  {
    shop: "dad",
    id: "camo-classic",
    name: "Camo Classic",
    price: 19.99,
    size: "20 oz skinny",
    description: "Classic woodland camo. You'll lose it in the truck. Worth it.",
    image: "images/camo-classic.svg",
    inStock: true,
    personalize: false,
    badge: "",
  },
  {
    shop: "dad",
    id: "game-day",
    name: "Game Day",
    price: 19.99,
    size: "20 oz skinny",
    description: "Built for tailgates, Sunday games, and loud opinions.",
    image: "images/game-day.svg",
    inStock: true,
    personalize: false,
    badge: "New",
  },
  {
    shop: "dad",
    id: "okayest-dad",
    name: "World's Okayest Dad",
    price: 19.99,
    size: "20 oz skinny",
    description: "The award he's been waiting for. Add his name for the full honor.",
    image: "images/okayest-dad.svg",
    inStock: true,
    personalize: true,
    personalizeHint: "His name (optional), e.g. Big Mike",
    badge: "Personalize it",
  },

  // --------------------------- CUSTOM --------------------------
  {
    shop: "custom",
    id: "custom-monogram",
    name: "Monogram",
    price: 34.99,
    size: "20 oz skinny",
    description: "Clean, classic initials in an elegant layout.",
    image: "images/custom-monogram.svg",
    inStock: true,
    personalize: true,
    personalizeHint: "Your initials, e.g. J C M",
    badge: "",
  },
  {
    shop: "custom",
    id: "custom-name",
    name: "Name or Phrase",
    price: 34.99,
    size: "20 oz skinny",
    description: "Any name, quote, or inside joke, styled just for you.",
    image: "images/custom-name.svg",
    inStock: true,
    personalize: true,
    personalizeHint: "The name or phrase you want",
    badge: "",
  },
  {
    shop: "custom",
    id: "custom-photo",
    name: "Photo Tumbler",
    price: 39.99,
    size: "20 oz skinny",
    description: "Your favorite photo wrapped around the tumbler. Email us the photo after you order.",
    image: "images/custom-photo.svg",
    inStock: true,
    personalize: true,
    personalizeHint: "Any notes about your photo (optional)",
    badge: "",
  },
  {
    shop: "custom",
    id: "custom-design",
    name: "Your Idea, Our Design",
    price: 44.99,
    size: "20 oz skinny",
    description: "Tell us your vision and we'll design it from scratch, then send a proof before pressing.",
    image: "images/custom-design.svg",
    inStock: true,
    personalize: true,
    personalizeHint: "Describe your idea (colors, theme, words)",
    badge: "",
  },
];
