// =====================================================================
//  YOUR TUMBLERS  —  add, remove, or edit products here.
//
//  Each product is one { ... } block. To add a new one, copy a whole
//  block (from { to },) and paste it below the last one, then change it.
//
//  shop        which tab it shows up in: "mom", "dad", "custom", or "all" (every tab).
//              Use "catalog" for a cup that only shows on the All page.
//  id          a short unique name, no spaces (used behind the scenes)
//  name        what customers see
//  price       in dollars, no $ sign (e.g. 29.99)
//  size        e.g. "20 oz skinny"
//  description a short note about the design (kept for your records; not shown on the shop cards)
//  image       the photo file inside the "images" folder
//  inStock     true = can be bought, false = shows "Sold out"
//  personalize true = shows a box where the buyer can type a name/text
//  personalizeHint  the grey hint text inside that box (optional)
//  badge       a little sticker on the photo, like "New" or "Our fave" (use "" for none)
//  tags        which groups it shows under on the All page, e.g. ["Anime", "Girl"]
//              (pick from the TAGS list at the bottom of this file)
// =====================================================================

window.PRODUCTS = [
  // ---------------------------- MOM ----------------------------
  {
    shop: "all",
    id: "pickle-party",
    name: "Pickle Party",
    price: 14.99,
    size: "20 oz skinny",
    description: "Our signature Pickled Sticker brand cup.",
    image: "images/pickle-party.png",
    inStock: true,
    personalize: false,
    badge: "Our brand cup",
    tags: ["Girl"],
  },
  {
    shop: "mom",
    id: "floral-dream",
    name: "Floral Dream",
    price: 19.99,
    size: "20 oz skinny",
    description: "Vintage tulips, roses and wildflowers wrapped all the way around.",
    image: "images/floral-dream.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
    tags: ["Girl"],
  },
  {
    shop: "mom",
    id: "sunset-glow",
    name: "Sunset Glow",
    price: 19.99,
    size: "20 oz skinny",
    description: "Dreamy pink-and-gold sunset over still water, with roses and golden drips.",
    image: "images/sunset-glow.jpg",
    inStock: true,
    personalize: false,
    badge: "",
    tags: ["Girl"],
  },
  {
    shop: "mom",
    id: "ocean-swirl",
    name: "Ocean Swirl",
    price: 19.99,
    size: "20 oz skinny",
    description: "Swirling turquoise and cobalt waves with white sea foam.",
    image: "images/ocean-swirl.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
    tags: ["Girl"],
  },
  {
    shop: "mom",
    id: "midnight-stars",
    name: "Midnight Stars",
    price: 19.99,
    size: "20 oz skinny",
    description: "Golden moons and stars in a dreamy purple night sky.",
    image: "images/midnight-stars.jpg",
    inStock: true,
    personalize: false,
    badge: "",
    tags: ["Girl"],
  },
  {
    shop: "mom",
    id: "mama-name",
    name: "Mama Name Tumbler",
    price: 19.99,
    size: "20 oz skinny",
    description: "Blush pink marble with peonies and her name in script (sample shows Betty).",
    image: "images/mama-name.jpg",
    inStock: true,
    personalize: true,
    personalizeHint: "Name to add, e.g. Betty or Mama",
    badge: "Personalize it",
    tags: ["Girl"],
  },

  {
    shop: "mom",
    id: "cool-vibes",
    name: "Cool Vibes",
    price: 19.99,
    size: "20 oz skinny",
    description: "Anime-style girl with headphones watching a city sunset.",
    image: "images/cool-vibes.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
    tags: ["Girl"],
  },

  {
    shop: "mom",
    id: "good-morning",
    name: "Good Morning",
    price: 19.99,
    size: "20 oz skinny",
    description: "Cozy sunlit kitchen, coffee in hand, messy bun energy.",
    image: "images/good-morning.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
    tags: ["Girl"],
  },

  {
    shop: "mom",
    id: "womans-best-friend",
    name: "Woman's Best Friend",
    price: 19.99,
    size: "20 oz skinny",
    description: "Happy golden retriever cozied up on a couch with a knit blanket.",
    image: "images/womans-best-friend.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
    tags: ["Girl"],
  },

  // ---------------------------- DAD ----------------------------
  {
    shop: "dad",
    id: "grill-master",
    name: "Grill Master",
    price: 19.99,
    size: "20 oz skinny",
    description: "For the guy who's been 'checking the burgers' for 45 minutes.",
    image: "images/grill-master.jpg",
    inStock: true,
    personalize: false,
    badge: "Dad fave",
    tags: ["Boy"],
  },
  {
    shop: "dad",
    id: "fishing-buddy",
    name: "Gone Fishin'",
    price: 19.99,
    size: "20 oz skinny",
    description: "Lake days, early mornings, and the one that got away.",
    image: "images/fishing-buddy.jpg",
    inStock: true,
    personalize: false,
    badge: "",
    tags: ["Boy"],
  },
  {
    shop: "dad",
    id: "camo-classic",
    name: "Camo Classic",
    price: 19.99,
    size: "20 oz skinny",
    description: "Classic woodland camo. You'll lose it in the truck. Worth it.",
    image: "images/camo-classic.jpg",
    inStock: true,
    personalize: false,
    badge: "",
    tags: ["Boy"],
  },
  {
    shop: "dad",
    id: "game-day",
    name: "Game Day",
    price: 19.99,
    size: "20 oz skinny",
    description: "Built for tailgates, Sunday games, and loud opinions.",
    image: "images/game-day.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
    tags: ["Boy"],
  },
  {
    shop: "dad",
    id: "okayest-dad",
    name: "Dad Name Tumbler",
    price: 19.99,
    size: "20 oz skinny",
    description: "Grill, fishing, football and tools around his name in bold script (sample shows Adam).",
    image: "images/dad-name.jpg",
    inStock: true,
    personalize: true,
    personalizeHint: "Name to add, e.g. Adam or Dad",
    badge: "Personalize it",
    tags: ["Boy"],
  },

  {
    shop: "dad",
    id: "dad-and-son",
    name: "Dad and Son",
    price: 19.99,
    size: "20 oz skinny",
    description: "Dad and son on the tailgate watching a desert sunset over the city.",
    image: "images/dad-and-son.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
    tags: ["Boy"],
  },

  {
    shop: "dad",
    id: "dad-and-daughter",
    name: "Dad and Daughter",
    price: 19.99,
    size: "20 oz skinny",
    description: "Dad reading a storybook with his little girl in a cozy lamp-lit room.",
    image: "images/dad-and-daughter.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
    tags: ["Boy"],
  },

  {
    shop: "dad",
    id: "big-but-still-armed",
    name: "Big but Still Armed",
    price: 19.99,
    size: "20 oz skinny",
    description: "Chunky cartoon dragon guarding his gold, armed and unbothered.",
    image: "images/big-but-still-armed.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
    tags: ["Boy"],
  },

  {
    shop: "dad",
    id: "pro-gun-pro-family",
    name: "Pro Gun, Pro Family",
    price: 19.99,
    size: "20 oz skinny",
    description: "Distressed American flag with a family badge reading Pro Gun, Pro Family.",
    image: "images/pro-gun-pro-family.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
    tags: ["Boy"],
  },

  // --------------------------- CUSTOM --------------------------
  {
    shop: "custom",
    id: "custom-monogram",
    name: "Monogram",
    price: 34.99,
    size: "20 oz skinny",
    description: "Clean, classic initials in an elegant layout.",
    image: "images/custom-monogram.jpg",
    inStock: true,
    personalize: true,
    personalizeHint: "Your initials, e.g. J C M",
    badge: "",
    tags: [],
  },
  {
    shop: "custom",
    id: "custom-name",
    name: "Name or Phrase",
    price: 34.99,
    size: "20 oz skinny",
    description: "Any name, quote, or inside joke, styled just for you.",
    image: "images/custom-name.jpg",
    inStock: true,
    personalize: true,
    personalizeHint: "The name or phrase you want",
    badge: "",
    tags: [],
  },
  {
    shop: "custom",
    id: "custom-photo",
    name: "Photo Tumbler",
    price: 39.99,
    size: "20 oz skinny",
    description: "Your favorite photo wrapped around the tumbler. Email us the photo after you order.",
    image: "images/custom-photo.jpg",
    inStock: true,
    personalize: true,
    personalizeHint: "Any notes about your photo (optional)",
    badge: "",
    tags: [],
  },
  {
    shop: "custom",
    id: "custom-design",
    name: "Your Idea, Our Design",
    price: 44.99,
    size: "20 oz skinny",
    description: "Tell us your vision and we'll design it from scratch, then send a proof before pressing.",
    image: "images/custom-design.jpg",
    inStock: true,
    personalize: true,
    personalizeHint: "Describe your idea (colors, theme, words)",
    badge: "",
    tags: [],
  },
  {
    shop: "catalog",
    id: "pool-day-pickle",
    name: "Pool Day Pickle",
    price: 19.99,
    size: "20 oz skinny",
    description: "A very unimpressed pickle guy chilling in the pool.",
    image: "images/pool-day-pickle.jpg",
    inStock: true,
    personalize: false,
    badge: "New",
    tags: ["Originals"],
  },
];

// The groups shown as buttons on the All page, in this order.
// Add a new name here to make a new group, then put it in a cup's tags.
window.TAGS = [
  "Anime", "Artsy", "Baseball Teams", "Boy", "Canvas", "Controversial", "Custom",
  "Elementary School", "Football Teams", "Girl", "High School", "Middle School",
  "Originals", "Political",
];
